spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.org/evoila-boxer/cf-service-broker-config
            
---
spring:
  profiles: default,development  
server:
  port: 8081
eureka:
  server: 
    enable-self-preservation: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
      
---
spring:
  profiles: cloud
server:
  port: 0
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443
  server: 
    enable-self-preservation: false
  client:
    serviceUrl:
      defaultZone: https://registry.onevoila.rocks/eureka/     
