---
spring:
  profiles: default,development  
server:
  port: 8080
eureka:
  server: 
    enable-self-preservation: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
      
---
spring:
  profiles: cloud
server:
  port: 0
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443
  server: 
    enable-self-preservation: false
  client:
    serviceUrl:
      defaultZone: https://registry.onevoila.rocks/eureka/
---
spring:
  profiles: bosh
server:
  port: ${SERVER_PORT:8080}
eureka:
  instance:
    hostname: localhost
  server:
    hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    port: ${EUREKA_SERVER_PORT:8761} 
    enable-self-preservation: false
  client:
    serviceUrl:
      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/                