---
resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/evoila/cf-service-broker
      branch: master

jobs:
  - name: maven-package
    plan:
    - aggregate:
      - get: git-repo
        trigger: true
    - task: maven-package
      privileged: true
      file: git-repo/pipeline/maven-package.yml
