---
spring:
  profiles: default,development  
server:
  port: 8082
eureka:
  instance:
    hostname: localhost    
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
---
spring:
  profiles: cloud
server:
  port: 0
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.secure-port}/eureka/

