---
spring:
  profiles: default,development  
server:
  port: 8082
eureka:
  instance:
    hostname: localhost    
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  file: registry.log
---
spring:
  profiles: cloud
server:
  port: 0
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.secure-port}/eureka/
logging:
  file: registry.log
---
spring:
  profiles: bosh
  application:
    name: eureka_server 
server:
  port: ${SERVER_PORT:8671}
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  file: registry.log