heat_template_version: 2013-05-23
description: Deployment Description for Elasticsearch
parameters:
  image_id:
    type: string
    description: Image used for servers
  keypair:
    type: string
    description: SSH key to connect to the servers
  flavor:
    type: string
    description: flavor used by the web servers
  network_id:
    type: string
    description: Network used by the server
  volume_size:
    type: number
    description: Size of the volume to be created.
  availability_zone:
    type: string
    description: The Availability Zone to launch the instance.
  es_password:
    type: string
    description: The password of the elasticsearch instance.
resources:
  nova_instance:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: flavor}
      image: {get_param: image_id}
      key_name: {get_param: keypair}
      networks: [{network: {get_param: network_id} }]
      user_data_format: RAW
      security_groups:
        - all
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            export REPOSITORY_ELASTICSEARCH="https://bitbucket.org/evoila-boxer/deployment-scripts-docker-openstack/raw/HEAD/elasticsearch"
            export REPOSITORY_MONIT="https://bitbucket.org/evoila-boxer/deployment-scripts-docker-openstack/raw/HEAD/monit"
            export REPOSITORY_MAIN="https://bitbucket.org/evoila-boxer/deployment-scripts-docker-openstack/raw/HEAD"
            
            wget $REPOSITORY_ELASTICSEARCH/elasticsearch-template.sh --no-cache
            chmod +x elasticsearch-template.sh
            ./elasticsearch-template.sh -p $es_password -e openstack
          params:
            $es_password: {get_param: es_password}
  cinder_volume:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: volume_size }
      availability_zone: { get_param: availability_zone }
  volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: cinder_volume }
      instance_uuid: { get_resource: nova_instance }
      mountpoint: /dev/vdc
