:imagesdir: assets

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Cloudfoundry Service-Broker

. link:../README.adoc[Getting Started]
. link:requirements.adoc[Requirements]
. Installation
.. link:setup.adoc[Setup]
.. link:deploymentscripts.adoc[Installation & Configuration Scripts]
. link:usage.adoc[Usage]
. link:repositories.adoc[Repositories]
. link:developers.adoc[Developers]
. link:contribution.adoc[Contribution]
. link:releasenotes.adoc[Release Notes]
. link:license.adoc[License]

== 3.2 Installation and Configuration Scripts
In the following sections we describe the structure and functionality of the deployment scripts for the services.

=== Type of Scripts
We developed scripts for automatic installation and configuration of different services for databases, logging and queueing.
The services available by now are

- PostgreSQL
- Redis
- MongoDB
- MySQL
- RabbitMQ
- Elasticsearch
- Logstash

We additionally created deployment scripts for monitoring with Monit.

All deployment scripts are working on different environments. All of them contain a build-in differentiation for the environment, so all scripts are working deployed to a virtual machine e.g. with a Heat script on OpenStack or as a container on Docker. The virtual machines used for testing run with Ubuntu 16.04 LTS.

=== Parametrization

For most services you can give parameters to the scripts for setting user, password and number of databases (or vhost).
You can find the possible parameters for any deployment scripts in the section <<servicespecific>>.

=== Central Data Path

One specialty is the configuration of our services for a high availability after a failure.
Developed using the cattle principle the data is stored on a separate volume, which can be backed up very easily.
This means, when an instance has a failure, a new service instance can be created and the stored volume can mounted to the new instance.

An automatic mechanism to mount old volumes in new instances is planned but not yet implemented.

=== Modularity

All deployment scripts for the installation of the services are modularized and subdivided in 5+1 modules.
This is important for an easier maintainability, further development and enhancements.
The modules are

- Start Script
- Central Template
- Installation
- Configuration
- Run
- Monit

link:usage.adoc[Next page ->]