
== Setup

=== Installation and Configuration Scripts
In the following sections we describe the structur and functionality of the deployment scripts for services.

==== Type of Scripts
We developed scripts for automatic installation and configuration of different services for databases, logging and queueing.
The services are avaiable at now are Postgres, Redis, MongoDB, MySQL, RabbitMQ, Elasticsearch and Logstash.
Additionaly we created deployment scripts for monit for monitoring.
All deployment scripts are working on different environments.
In all deployment scripts is an build-in differentiation for the environment.
So all scripts are working on Openstack (or other full Virtual Machine provider e.g. VMware etc.) and containerized on Docker

==== Parametrization

For most services you can give parameters to the scripts for setting user, password and number of databases (or vhost)
parameters. The possible parameters for any deployment scripts you can find in the section <<servicespecific>>.

==== Central Data Path

==== Modularity

All deployment scripts for the Installation of the services are modularized and subdivided in 5 modules.
This is important for an easier mantainability, further development and enhancements
The modules are Start Script, Central Template, Installation, Configuration, Run and Monit.
The module "Monit" has the same structure (without the module Monit).


===== Module 1: Start Script

`[exampleservice]-start-script.sh`

The first skript is the start skript.
Its only task is to set some very basic things like the path to the repositorys, loading and execution of the central template.
The repositories are specified there is the main repository and the script specific subrepository.
And this is the place were you can embed your parameters for the central template.

TIP: you can use this script as a standalone script or embed it as a snippet in your own code. +
Additionaly this is the place for handing over the parameters to the Central Template.

include::snippets/setup/start-script-sh.adoc[]


===== Module 2: Central Template

`[exampleservice]-template.sh`

All following steps in the deployment scrips are organized in the Central Template.
In the Central Template the definition of the most needed variables are bundled.
The following chart describes the common variables defined in `[exampleservice]-template.sh` and used in all scripts.
Specific variables for some scripts are listed in the section <<servicespecific>>.

.common variables
[width="80%",cols="3"]
[frame="topbot",grid="none"]
[options="header"]
|======
|Property|Name of variable|Description
|Version of application|$EXAMPLESERVICE_VERSION [red]#*#|Version of the installed application
|Configuration Path|$CONF_PATH [red]#*#| Path to the configuration files
|Data directory|$DATA_DIR [red]#*#|Variable for the data directory (in the scripts set to `/data/` )
|Check path|$CHECK_PATH|Path used for the scripts to check if it is a new installation or is the service still installed
|Openstack start command|$OPENSTACK_START|Command to start service on Openstack as environment
|Openstack stop command|$OPENSTACK_STOP|Command to stop service on Openstack as environment
|Docker start command|$DOCKER_START|Command to start service on Docker as environment
|Docker stop command|$DOCKER_STOP|Command to stop service on Docker as environment
|Environment variable|$ENVIRONMENT| This variable is used for the differentioation between the environments used for the service instances
|||[red]#_* the marked variables have different names in some services_#
|======



As a second step the Central Template handles the parameters given from the start script or the snippet of the start script you embeded in your code.
After that they will be exported for usage in following child scripts (modules).
Then the different modules will be loaded and execuded in the appropriate order.
In the same way a service specific "monit controll file" `[exampleservice]-monitrc` for the later following configuration of monit will be loaded.
As last step monit will be installed or executed for monitoring and service recovery (for detailed description read the topic <<monit>>).

include::snippets/setup/template-sh.adoc[]


===== Module 3: Installation

`[exampleservice]-install.sh`

Module 3 is the installation
First this module prepairs environment for installation with the following steps.

.Preinstall preperations:
- creates groups on the host

- creates user for the service on the host

- creates home directoies for the user

- sets write/read permissions and ownership for created folders if needed

After this is done this script installs the service itself.

When all tasks of this module are done the Central Template resumes the controll to load and execute module 4 (Configuration).

===== Module 4: Configuration `[exampleservice]-configuration.sh`

When the installation is succesfully done this script can configure the service.

.Typical steps of the scripts
- generating the administrative user of the service
- configuring password for this user
- applying a database with a given name or a given quantity

After all tasks are done the Central Template resumes the controll to load and execute the run script.

[[run]]
===== Module 5: Run

`[exampleservice]-run.sh`

This Module starts the ready configurated service.
When all tasks of this module are done the Central Template resumes the controll.

IMPORTANT: An important point here is the differentiation between Openstack and Docker. +
In detail it is described in the section "<<environment>>" of the documentation.

It is reallized directly in the scripts so you have nothing to do unless you have to set the environment parameter, described in module 1.

When all tasks of this module are done the Central Template resumes the controll for installing the monitoring tool for service recovery (monit).

[[monit]]
===== Module 6: Monit

`monit-start-script.sh`

As last module this installs and runs a monit. Monit is here used for monitoring and service recovery.
The installation of monit follows the same structure as it is described from Module 1 to 5.
When it is allready installed it will be only execuded.

[[environment]]
=== Environment specific

We developt the scripts for running on different environments.
Most code is similar for both of the used environments.
A divergence is requiered for the execution of processes in docker as environment in mostly all scripts. The different start and stop commands are included in the current Central Template.
Likewise in a few scripts there is a little differentiation in the configuration files nessesary.

.Distinctions between openstack and docker
[NOTE]
Subtile distinctions between openstack and docker embeded direct in the code
to realize an easier maintainability and further development and enhancements.

==== Openstack
On Openstack most processes are started as a service.

==== Docker
On Docker

[[servicespecific]]
=== Service specific

Generally all deployment scripts have the same structure.

==== Postgres

==== Redis

==== MongoDB

==== MySQL

Custom apparmor configuration

CAUTION: If you change any pathes of the MySQL installation you have to apapt the apparmor configuration appropriate. +
Otherwise Apparmor will prevent MySQL to use to this folders.


==== RabbitMQ

==== Elasticsearch

==== Logstash

==== Monit

=== Central Logging

In a next step a central logging for the services will be added.

include::test.adoc[]
