:imagesdir: assets

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Cloudfoundry Service-Broker

. link:../README.adoc[Getting Started]
. link:requirements.adoc[Requirements]
. Installation
.. link:setup.adoc[Setup]
.. link:deploymentscripts.adoc[Installation & Configuration Scripts]
. link:usage.adoc[Usage]
. link:repositories.adoc[Repositories]
. link:developers.adoc[Developers]
. link:license.adoc[License]

== 3.1 Setup

=== Deployment

There is one deployable instance for each implemented service broker. The setup also contains a prepared cloud config server and a eureka server (called registry) for service discovery (both servers are optional). The service discovery is not fully integrated in the service brokers yet. So the cloud config server has to be introduced to the service brokers via configuration. In the future this will be handled by the registry.

A minimal deployment either is local with configuration file and consists of:

- A single Service Broker

or consists of:

- Registry Server
- Cloud Config Server
- Service Broker

There is only one instance of the registry and cloud config server needed to run several Service Brokers.

There exist different possibilities to deploy the service brokers:

- Executable JAR (Java Process with embedded Standalone Tomcat Server)
- Linux init.d/system.d service
- Servlet Container on for example Tomcat Server
- Cloud Foundry Application
- bosh deployment

If you want to run the service broker locally, we encourage you to start the service broker either as Java Process or Linux init.d service. In an production environment we see a deployment as a Cloud Foundry Application or bosh release as more reasonable.

You also need a database to store management data and inner status of the service broker. You can use

- MongoDB 

==== Java Process (Standalone Tomcat Server)

As the service brokers as well as the cloud config server and the registry are build as Spring Boot Applications, they can be deployed as standalone Tomcat Server without any additional components needed. Only a Java Virtual Machine supporting Java 8 or later is needed. Download the latest release, switch over to the download directory and run:

`java -jar registry.jar` +
`java -jar cloud-config.jar` +
`java -jar ssb-<service_name>.jar`

==== Linux init.d/system.d service

Newer Spring Boot versions support the deployment as so called 'fully executable jar'. That means the JAR-file can be executed directly. The provided JAR-files of the releases are build as fully executable JARs. How to start them as init.d or system.d service can be found under:

==== Servlet Container on existing Server

To be added soon.

==== Cloud Foundry Application
The applications are build to run on Cloud Foundry. There are link:https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html[manifest files] provided to push the applications to Cloud Foundry.

WARNING: The manifest files are optimized for our DevOps team. So they use the path structure of the code repo. If you want to use it with the pre-build releases, download the manifest file and change the link:https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#path[path] to JAR-files according to your file system path. We advice you to put all necessary JAR-files in the "target" folder of your project.

The following instructions require the installation of a Cloud Foundry CLI on your system.

1. Navigate to the folder which contains the manifest file: +
`cd ./cf-service-broker`

2. Login your Cloud Foundry CLI to your Cloud Foundry Environment: +
`cf login -u <user> -a <url_of_api_endpoint> -p <password> -o <organization> -s <space>`

3. Push the application to the Cloud Foundry environment using the manifest file: +
`cf push`

NOTE: If you wish to push with a manifest file that is not named 'manifest.yml', you have to add the `-f <path_to_the_manifest_file>` parameter.

Now lean back and watch the deployment.

NOTE: If your cloud config server uses a git repository with SSL and authentication, you can copy the `manifest-with-credentials-example.yml` file in the config subproject and rename it to `manifest-with-credentials.yml`. There exists a `.gitignore` entry, so it will not be uploaded to your git repository. In the files you find placeholder variables to insert your credentials. Use this manifest file to deploy the cloud config server. Or copy it to the parent directory. Then the deployment of all projects is modified and the credentials are provided to the cloud config server.

==== Bosh Deployment

To be added soon.

=== Cloud Config Repository

WARNING: This part is currently reworked.

To use a git repository with your cloud config server, you have to provide one.

1. You have to create a new git repository project first (for example on github).

2. Then you need the url of the repository (for example `https://example.com/config`)

3. Insert the url of your repository to the `bootstrap.yml` of your cloud config server or provide them as envrionment variable in your `manifest.yml`.

4. Then add the following files to your repository:

icon:file[] `application.yml` - contains the configuration options for all applications. For a better understanding see this link:snippets/setup/cloud-config/application.yml.adoc[example].

- *spring.profiles:* The spring profile, for which the following informations applies.
- *spring.application_name:* The name of your project.
- *spring.ssl.acceptselfsigned:* Boolean to tell java to accept self signed ssl certificates or not.
- *info.app.name:* The name of your Service Broker.
- *info.app.description:* A description of your Service Broker.
- *info.app.version:* The version number of your Service Broker.
- *login.username:* Your username for creating Service Brokers.
- *login.password:* Your password for creating Service Brokers.
- *login.role:* Your role in the organization.
- *spring.data.mongodb.host:* The ip of your database where you store user informations.
- *spring.data.mongodb.port:* The port of this database.
- *spring.data.mongodb.database:* The name of this database.
- *spring.data.mongodb.username:* Your username to log in to this database.
- *spring.data.mongodb.password:* Your password to log in to this database.
- *existing.endpoint.hosts:* A list with the IP(s) of your Service Broker database (cluster).
- *existing.endpoint.port:* The port of this database.
- *existing.endpoint.database:* The name of this database.
- *existing.endpoint.username:* Your username to log in to this database.
- *existing.endpoint.password:* Your password to log in to this database.
- *logging.file:* The file you want to save the log informations in, ex. ${LOG_FILE:cf-service-broker-mongodb.log}
- *logging.level.root:* The level of logging (error, warn, info, debug or trace), ex. ${LOG_LEVEL_ROOT:INFO}
- *backend.ports.default:*
- *backend.connection.timeouts:*
- *mongodb.security.key.length:* The length of your MongoDB security key.
- *haproxy.uri:* The url of your HaProxy backend, ex. https://haproxy.example.com/agents/Default-HaProxy-Agent/schemas?type=listen.
- *haproxy.auth.token:* The authentication token for your HaProxy
- *deployment.repo.service:* Url of the repository that contains all your service specific scripts.
- *deployment.repo.monit:* Url of the repository that contains all your monit scripts.

You can also store informations from your application.yml in your manifest.yml. Let's say you want to store the informations about the HaProxy in your manifest.yml. Simply go to the "env" passage and enter in all caps and underscores for every tab:

    env:
        HAPROXY_URI: (...)
        HAPROXY_AUTH_TOKEN: (...)

icon:file[] `<service_name>-<profile>.yml` - contains the configuration options of the service broker (use `rabbitmq` for RabbitMQ service broker) started with the profile, as shown in this link:snippets/setup/cloud-config/service-broker-profile.yml.adoc[example].

NOTE: We provided support for the profiles `development`, `default`, `cloud` and `bosh`. `cloud` is used by us for deployments to a cloud foundry environment as applications.

4. Add your custom properties to the property files

5. Now the properties from your repository are used when starting the service broker, cloud config server or registry server. Please make sure to start the cloud config server before the service brokers, because it enables the access towards the repository.

NOTE: Using the `bootstrap.yml` you can use different property sources for different profiles. For further information see link:http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_spring_cloud_config[spring cloud config documentation].

link:deploymentscripts.adoc[Next page ->]